# Generated by Django 5.1 on 2024-08-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_client_updated_at_alter_project_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'client')},
        ),
    ]
